package org.barber.stdfhandler;

import org.barber.stdfhandler.file.*;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

class FullTest extends StdfTest {

    @Test
    void createAndPrintFullFile() throws IOException {

        FileBuilder builder = FileHandler.newInstance().getBuilder()
                .addRecord(RecordAtr.newInstance()
                        .setModTim(TYPE_TIME_EXPECTED_VALUE)
                        .setCmdLine(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordVur.newInstance()
                        .setUpdNam(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordMir.newInstance()
                        .setSetupT(TYPE_TIME_EXPECTED_VALUE)
                        .setStartT(TYPE_TIME_EXPECTED_VALUE)
                        .setStatNum(TYPE_U1_EXPECTED_VALUE)
                        .setModeCod(TYPE_C1_EXPECTED_VALUE)
                        .setRtstCod(TYPE_C1_EXPECTED_VALUE)
                        .setProtCod(TYPE_C1_EXPECTED_VALUE)
                        .setBurnTim(TYPE_U2_EXPECTED_VALUE)
                        .setCmodCod(TYPE_C1_EXPECTED_VALUE)
                        .setLotId(TYPE_CN_EXPECTED_VALUE)
                        .setPartTyp(TYPE_CN_EXPECTED_VALUE)
                        .setNodeNam(TYPE_CN_EXPECTED_VALUE)
                        .setTstrTyp(TYPE_CN_EXPECTED_VALUE)
                        .setJobNam(TYPE_CN_EXPECTED_VALUE)
                        .setJobRev(TYPE_CN_EXPECTED_VALUE)
                        .setSblotId(TYPE_CN_EXPECTED_VALUE)
                        .setOperNam(TYPE_CN_EXPECTED_VALUE)
                        .setExecTyp(TYPE_CN_EXPECTED_VALUE)
                        .setExecVer(TYPE_CN_EXPECTED_VALUE)
                        .setTestCod(TYPE_CN_EXPECTED_VALUE)
                        .setTstTemp(TYPE_CN_EXPECTED_VALUE)
                        .setUserTxt(TYPE_CN_EXPECTED_VALUE)
                        .setAuxFile(TYPE_CN_EXPECTED_VALUE)
                        .setPkgTyp(TYPE_CN_EXPECTED_VALUE)
                        .setFamlyId(TYPE_CN_EXPECTED_VALUE)
                        .setDateCod(TYPE_CN_EXPECTED_VALUE)
                        .setFacilId(TYPE_CN_EXPECTED_VALUE)
                        .setFloorId(TYPE_CN_EXPECTED_VALUE)
                        .setProcId(TYPE_CN_EXPECTED_VALUE)
                        .setOperFrq(TYPE_CN_EXPECTED_VALUE)
                        .setSpecNam(TYPE_CN_EXPECTED_VALUE)
                        .setSpecVer(TYPE_CN_EXPECTED_VALUE)
                        .setFlowId(TYPE_CN_EXPECTED_VALUE)
                        .setSetupId(TYPE_CN_EXPECTED_VALUE)
                        .setDsgnRev(TYPE_CN_EXPECTED_VALUE)
                        .setEngId(TYPE_CN_EXPECTED_VALUE)
                        .setRomCod(TYPE_CN_EXPECTED_VALUE)
                        .setSerlNum(TYPE_CN_EXPECTED_VALUE)
                        .setSuprNam(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordRdr.newInstance()
                        .setRtstBin(List.of(TYPE_U2_EXPECTED_VALUE, TYPE_U2_EXPECTED_VALUE)))
                .addRecord(RecordSdr.newInstance()
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteGrp(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(List.of(TYPE_U1_EXPECTED_VALUE, TYPE_U1_EXPECTED_VALUE))
                        .setHandTyp(TYPE_CN_EXPECTED_VALUE)
                        .setHandId(TYPE_CN_EXPECTED_VALUE)
                        .setCardTyp(TYPE_CN_EXPECTED_VALUE)
                        .setCardId(TYPE_CN_EXPECTED_VALUE)
                        .setLoadTyp(TYPE_CN_EXPECTED_VALUE)
                        .setLoadId(TYPE_CN_EXPECTED_VALUE)
                        .setDibTyp(TYPE_CN_EXPECTED_VALUE)
                        .setDibId(TYPE_CN_EXPECTED_VALUE)
                        .setCablTyp(TYPE_CN_EXPECTED_VALUE)
                        .setCablId(TYPE_CN_EXPECTED_VALUE)
                        .setContTyp(TYPE_CN_EXPECTED_VALUE)
                        .setContId(TYPE_CN_EXPECTED_VALUE)
                        .setLasrTyp(TYPE_CN_EXPECTED_VALUE)
                        .setLasrId(TYPE_CN_EXPECTED_VALUE)
                        .setExtrTyp(TYPE_CN_EXPECTED_VALUE)
                        .setExtrId(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordPcr.newInstance()
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                        .setPartCnt(TYPE_U4_EXPECTED_VALUE)
                        .setRtstCnt(TYPE_U4_EXPECTED_VALUE)
                        .setAbrtCnt(TYPE_U4_EXPECTED_VALUE)
                        .setGoodCnt(TYPE_U4_EXPECTED_VALUE)
                        .setFuncCnt(TYPE_U4_EXPECTED_VALUE))
                .addRecord(RecordHbr.newInstance()
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                        .setHbinNum(TYPE_U2_EXPECTED_VALUE)
                        .setHbinCnt(TYPE_U4_EXPECTED_VALUE)
                        .setHbinPf(TYPE_C1_EXPECTED_VALUE)
                        .setHbinNam(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordSbr.newInstance()
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                        .setSbinNum(TYPE_U2_EXPECTED_VALUE)
                        .setSbinCnt(TYPE_U4_EXPECTED_VALUE)
                        .setSbinPf(TYPE_C1_EXPECTED_VALUE)
                        .setSbinNam(TYPE_CN_EXPECTED_VALUE))
                .addRecord(RecordPmr.newInstance()
                        .setPmrIndx(TYPE_U2_EXPECTED_VALUE)
                        .setChanTyp(TYPE_U2_EXPECTED_VALUE)
                        .setChanNam(TYPE_CN_EXPECTED_VALUE)
                        .setPhyNam(TYPE_CN_EXPECTED_VALUE)
                        .setLogNam(TYPE_CN_EXPECTED_VALUE)
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(TYPE_U1_EXPECTED_VALUE))
                .addRecord(RecordPgr.newInstance()
                        .setGrpIndx(TYPE_U2_EXPECTED_VALUE)
                        .setGrpNam(TYPE_CN_EXPECTED_VALUE)
                        .setPmrIndx(List.of(TYPE_U2_EXPECTED_VALUE, TYPE_U2_EXPECTED_VALUE)))
                .addRecord(RecordPlr.newInstance().setValues(
                        List.of(TYPE_U2_EXPECTED_VALUE, TYPE_U2_EXPECTED_VALUE),
                        List.of(TYPE_U2_EXPECTED_VALUE, TYPE_U2_EXPECTED_VALUE),
                        List.of(TYPE_U1_EXPECTED_VALUE, TYPE_U1_EXPECTED_VALUE),
                        List.of(TYPE_CN_EXPECTED_VALUE, TYPE_CN_EXPECTED_VALUE),
                        List.of(TYPE_CN_EXPECTED_VALUE, TYPE_CN_EXPECTED_VALUE),
                        List.of(TYPE_CN_EXPECTED_VALUE, TYPE_CN_EXPECTED_VALUE),
                        List.of(TYPE_CN_EXPECTED_VALUE, TYPE_CN_EXPECTED_VALUE)))
                .addWafer(WaferData.newInstance()
                        .setWir(RecordWir.newInstance()
                                .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                                .setSiteGrp(TYPE_U1_EXPECTED_VALUE)
                                .setStartT(TYPE_TIME_EXPECTED_VALUE)
                                .setWaferId(TYPE_CN_EXPECTED_VALUE))
                        .setWcr(RecordWcr.newInstance()
                                .setWafrSiz(TYPE_R4_EXPECTED_VALUE)
                                .setDieHt(TYPE_R4_EXPECTED_VALUE)
                                .setDieWid(TYPE_R4_EXPECTED_VALUE)
                                .setWfUnits(TYPE_U1_EXPECTED_VALUE)
                                .setWfFlat(TYPE_C1_EXPECTED_VALUE)
                                .setCenterX(TYPE_I2_EXPECTED_VALUE)
                                .setCenterY(TYPE_I2_EXPECTED_VALUE)
                                .setPosX(TYPE_C1_EXPECTED_VALUE)
                                .setPosY(TYPE_C1_EXPECTED_VALUE))
                        .setWrr(RecordWrr.newInstance()
                                .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                                .setSiteGrp(TYPE_U1_EXPECTED_VALUE)
                                .setFinishT(TYPE_TIME_EXPECTED_VALUE)
                                .setPartCnt(TYPE_U4_EXPECTED_VALUE)
                                .setRtstCnt(TYPE_U4_EXPECTED_VALUE)
                                .setAbrtCnt(TYPE_U4_EXPECTED_VALUE)
                                .setGoodCnt(TYPE_U4_EXPECTED_VALUE)
                                .setFuncCnt(TYPE_U4_EXPECTED_VALUE)
                                .setWaferId(TYPE_CN_EXPECTED_VALUE)
                                .setFabwfId(TYPE_CN_EXPECTED_VALUE)
                                .setFrameId(TYPE_CN_EXPECTED_VALUE)
                                .setMaskId(TYPE_CN_EXPECTED_VALUE)
                                .setUsrDesc(TYPE_CN_EXPECTED_VALUE)
                                .setExcDesc(TYPE_CN_EXPECTED_VALUE))
                        .addPart(PartData.newInstance()
                                .setPir(RecordPir.newInstance()
                                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                                        .setSiteNum(TYPE_U1_EXPECTED_VALUE))
                                .addPtr(RecordPtr.newInstance()
                                        .setTestNum(TYPE_U4_EXPECTED_VALUE)
                                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                                        .setTestFlg(TYPE_B1_DEFAULT_VALUE)
                                        .setParmFlg(TYPE_B1_DEFAULT_VALUE)
                                        .setResult(TYPE_R4_EXPECTED_VALUE)
                                        .setTestTxt(TYPE_CN_EXPECTED_VALUE)
                                        .setAlarmId(TYPE_CN_EXPECTED_VALUE)
                                        .setOptFlag(TYPE_B1_DEFAULT_VALUE)
                                        .setResScal(TYPE_I1_EXPECTED_VALUE)
                                        .setLlmScal(TYPE_I1_EXPECTED_VALUE)
                                        .setHlmScal(TYPE_I1_EXPECTED_VALUE)
                                        .setLoLimit(TYPE_R4_EXPECTED_VALUE)
                                        .setHiLimit(TYPE_R4_EXPECTED_VALUE)
                                        .setUnits(TYPE_CN_EXPECTED_VALUE)
                                        .setcResfmt(TYPE_CN_EXPECTED_VALUE)
                                        .setcLlmft(TYPE_CN_EXPECTED_VALUE)
                                        .setcHlmft(TYPE_CN_EXPECTED_VALUE)
                                        .setLoSpec(TYPE_R4_EXPECTED_VALUE)
                                        .setHiSpec(TYPE_R4_EXPECTED_VALUE))
                                .setPrr(RecordPrr.newInstance()
                                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                                        .setPartFlg(TYPE_B1_EXPECTED_VALUE)
                                        .setNumTest(TYPE_U2_EXPECTED_VALUE)
                                        .setHardBin(TYPE_U2_EXPECTED_VALUE)
                                        .setSoftBin(TYPE_U2_EXPECTED_VALUE)
                                        .setXCoord(TYPE_I2_EXPECTED_VALUE)
                                        .setYCoord(TYPE_I2_EXPECTED_VALUE)
                                        .setTestT(TYPE_U4_EXPECTED_VALUE)
                                        .setPartId(TYPE_CN_EXPECTED_VALUE)
                                        .setPartTxt(TYPE_CN_EXPECTED_VALUE)
                                        .setPartFix(TYPE_BN_EXPECTED_VALUE))))
                .addRecord(RecordTsr.newInstance()
                        .setHeadNum(TYPE_U1_EXPECTED_VALUE)
                        .setSiteNum(TYPE_U1_EXPECTED_VALUE)
                        .setTestTyp(TYPE_C1_EXPECTED_VALUE)
                        .setTestNum(TYPE_U4_EXPECTED_VALUE)
                        .setExecCnt(TYPE_U4_EXPECTED_VALUE)
                        .setFailCnt(TYPE_U4_EXPECTED_VALUE)
                        .setAlrmCnt(TYPE_U4_EXPECTED_VALUE)
                        .setTestNam(TYPE_CN_EXPECTED_VALUE)
                        .setSeqName(TYPE_CN_EXPECTED_VALUE)
                        .setTestLbl(TYPE_CN_EXPECTED_VALUE)
                        .setOptFlag(TYPE_B1_DEFAULT_VALUE)
                        .setTestTim(TYPE_R4_EXPECTED_VALUE)
                        .setTestMin(TYPE_R4_EXPECTED_VALUE)
                        .setTestMax(TYPE_R4_EXPECTED_VALUE)
                        .setTstSums(TYPE_R4_EXPECTED_VALUE)
                        .setTstSqrc(TYPE_R4_EXPECTED_VALUE))
                .addRecord(RecordMrr.newInstance()
                        .setFinishT(TYPE_TIME_EXPECTED_VALUE)
                        .setDispCod(TYPE_C1_EXPECTED_VALUE)
                        .setUsrDesc(TYPE_CN_EXPECTED_VALUE)
                        .setExcDesc(TYPE_CN_EXPECTED_VALUE));

        ByteArrayOutputStream outputStream = builder.toStream();
        FileHandler fileHandler = FileHandler.newInstance();
        FileImage image = fileHandler.read(new ByteArrayInputStream(outputStream.toByteArray()));
        System.out.println(image.toString());

    }
}
